VENDEDORES = {
    "V001": "Ulises Sihnue Vallejo Ochoa",
    "V002": "Heladia Flores Hernández",
    "V003": "Gabriel Damián Sarmiento Rosas",
    "V004": "Jesús Rodrigo Chávez Bolio",
    "V005": "Nuby Beatriz",
    "V006": "Tolentino Cruz Aparicio",
    "V007": "Marian Aranza Castillo",
    "V008": "Rafael Ruiz Chaparro",
    "V009": "Juan Manuel Segura Dimas",
    "V010": "Raymundo Flores Morales",
    "V011": "Luis Antonio Aguilar García",
    "V012": "Kiefer Rodriguez",
    "V013": "Lorena Velazquez",
    "V014": "Vanessa Judith Escobar Armendariz",
    "V015": "Verónica Cuellar",
    "V016": "Raúl Duarte Martínez",
    "V017": "Mayno Adolfo Cruz",
}