VENDEDORES = {
    "V001": "Ulises Sihnue Vallejo Ochoa",
    "V002": "Heladia Flores Hernández",
    "V003": "Gabriel Damián Sarmiento Rosas",
    "V004": "Jesús Rodrigo Chávez Bolio",
    "V005": "Nuby Beatriz",
    "V006": "Tolentino Cruz Aparicio",
    "V007": "Marian Aranza Castillo",
    "V008": "Rafael Ruiz Chaparro",
    "V009": "Juan Manuel Segura Dimas",
    "V010": "Raymundo Flores Morales",
    "V011": "Luis Antonio Aguilar García",
    "V012": "Kiefer Rodriguez",
    "V013": "Lorena Velazquez",
    "V014": "Vanessa Judith Escobar Armendariz",
    "V015": "Verónica Cuellar",
    "V016": "Raúl Duarte Martínez",
    "V017": "Mayno Adolfo Cruz",
    "V018" : "Miguel Alberto Soto Lugo",
    "V019" : "Tolentino Cruz Aparicio",
    "V020" : "Juan Manuel Segura Dimas", 
    "V021" : "Valeria Duran Santanta",
    "V022" : "Alma Delia Torres Gonzalez",
    "V023" : "Miriam Gil",
    "V024" : "Oznar Sayd Hernandez Monroy",
    "V025" : "Juan Pablo Herrera Maldonado",
    "V026" : "Oscar Garcia",
    "V027" : "Yolanda Vazquez Alcazar",
    "V028" : "Maria del Rosario Mejia Baez",
    "V029" : "Javier Alberto Torres",
    "V030" : "Edgar Castelo Virgen",
    "V031" : "Susan Avalos Leyva",
    "V032" : "Maria de los angeles Aguijoza",
    "V033" : "Gabriel Damian  Sarmiento Rosado",
    "V034" : "Manuel Adalberto Andrade Peraza",
    "V035" : "José Leonardo Morales Olmedo",
    "V036" : "Mario Iván Muñiz Valadez",
    "V037" : "Jose Angel Perez Lopez",
    "V038" : "Alexis Santiago Velasco",
    "V039" : "Sulma Hernández Vallarta",
    "V040" : "Jesús Enrique Robles Garcia",
    "V041" : "Esmeralda Zavala",
    "V042" : "Victor Manuel",
    "V043" : "Ricardo Espinosa Solorio",
    "V044": "Aliza Adriana De la Cruz del Campo",
    "V045": "Carmen Berenice Hernández Ruiz",
    "V046": "Rosalba Sandoval",
    "V047": "Oscar Salguero",
    "V048": "Armando Ornelas",
    "V049": "Angel Reyes Piñon Arredondo",
    "V050": "Mauricio Salas Piña",
    "V051": "Juan Carlos Figueroa Solorio",
    "V052": "Jose Angel Peres Lopez",
    "V053": "Julio Cesar Gualajara Flores",
    "V054": "Jorge Omar Gómez Ramos",
    "V055": "Hugo Mauricio Estrada Mejia",
    "V056": "Luis Francisco Matias Barajas",
    "V057": "Luis Andres Victorio Valdovinos",
    "V058": "Jesús Juárez",
    "V059": "Miguel Angel Castellanos",
    "V060": "Ahtziri Olivo Paredes",
    "V061": "Zenon Medina Salgado",
    "V062": "Nancy Felix",
    "V063": "Mariana Martinez",
    "V064": "Ity yelania Vidal Huerta",
    "V065": "Leonardo Estefanía Castillo Martinez",
    "V066": "Irma Alfonzo Valdez",
    "V067": "Alma America Acosta Torres",
    "V068": "Gerardo Alejandro Vargas Dueñas",
    "V069": "Francisco Javier Madrigal",
    "V070": "Cristhian Guerrero",
    "V071":"Davisa Amador Garcia",
    "V072":"Victor Hugo Moron Avalos",
    "V073":"Arturo Montes Calderon",
    "V074":"Juan Diego Camacho Camacho",
    "V075":"Rogelio Ayala Bustos",
    "V076":"Sergio Castillo Martinez",
    "V077":"Raúl Plata Curiel",
    "V078":"Diana Karina Ontiveros Escamilla",
    "V079":"Michel Alicia Hilario Ayala",
    "V080":"Antonio Valenzuela Barron",
    "V081":"Juan Gerardo Macias Hernandez",
    "V082":"José Manuel Soto Tapia",
    "V083":"José Labarrera Madrigal",
    "V084":"David Cornejo Flores",
    "V085":"Noemi Vazquez del Mercado Gutierrez",
    "V086":"Vinicio Hernández Valero",
    "V087":"Radu Rogelio Plata",
    "V088":"Guillermo Arteaga López",
    "V089":"María Leticia Contreras Villalobos",
    "V090":"Juan José González Morales",
    "V091":"Luis Gerardo Rangel Chavez",
    "V092":"Carmen Rocio Lino Arredondo",
    "V093":"Luis Negrete",
    "V094":"Karina Perez Sanchez"
}